-- Sample users with BCrypt hashed passwords
-- Passwords: admin=admin, johnd=foo, janed=ddd
-- Note: These are hashes generated by BCrypt
INSERT INTO users (username, firstname, lastname, password, role) VALUES
  ('admin', 'Foo', 'Bar', '$2a$10$b.PoKj6VYQ2/RQvj88VJKuHO5sLZW9qJLJ7EQVfZe5oeYl2yjgVHq', 1),
  ('johnd', 'John', 'Doe', '$2a$10$DXJRNJ4JV6/AL.nJjR6ftuQVVJq68NmXPg1w75jj2yK2HFVJFJWBu', 0),
  ('janed', 'Jane', 'Doe', '$2a$10$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5EQaYzYh5i1CW', 0);