[SERVICE]
    Flush              1
    Daemon             Off
    Log_Level          info

[INPUT]
    Name               forward
    Listen             0.0.0.0
    Port               24224
    Tag                host.java.log

[FILTER]
    Name               modify
    Match              host.java.log
    Add                service.name host-java-app
    Add                observer.type fluent-bit

[OUTPUT]
    Name               es
    Match              host.java.log
    Host               es01
    Port               9200
    HTTP_User          elastic
    HTTP_Passwd        ${ELASTIC_PASSWORD}
    Index              host-java-logs
    Suppress_Type_Name On
    Generate_ID        On
    tls                On
    tls.verify         On
    tls.ca_file        /certs/ca/ca.crt
