apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  namespace: app
  labels:
    app: log-message-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-app
      containers:
      - name: log-processor
        image: kan2nd/microapp:log-processor
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_REDIS_PORT
        - name: REDIS_CHANNEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_CHANNEL
        - name: ZIPKIN_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ZIPKIN_URL
        - name: ELASTIC_APM_SERVER_URL
          value: "http://fleet-server.monitor.svc.cluster.local:8200"
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: elastic-apm-secret
              key: apm-secret-token
        - name: ELASTIC_APM_SERVICE_NAME
          value: "log-message-processor"
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
