apiVersion: v1
kind: Secret
metadata:
  name: elastic-apm-secret
  namespace: app
type: Opaque
stringData:
  elastic-password: "changeme"
  apm-secret-token: "apm-secret-token-change-me"
  fleet-enrollment-token: "fleet-enrollment-token-change-me"
