apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-config
  namespace: monitor
data:
  STACK_VERSION: "9.3.1"
  CLUSTER_NAME: "monitor-cluster"
  LICENSE: "basic"
  MONITOR_VM_IP: "192.168.96.136"

---
apiVersion: v1
kind: Secret
metadata:
  name: monitor-secrets
  namespace: monitor
type: Opaque
stringData:
  ELASTIC_PASSWORD: "changeme"        # change this
  KIBANA_PASSWORD: "changeme"         # change this
  ENCRYPTION_KEY: "changeme_generate_a_new_32_byte_hex_key"  # generate with: openssl rand -hex 32
  ELASTIC_APM_SECRET_TOKEN: "supersecrettoken"
