apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: zipkin
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9411
    targetPort: http
    protocol: TCP
    nodePort: 30411
  selector:
    service: zipkin